friends:
  descriptions: false
  groups-in-common: true
  friends-in-common: true
  join-date: true
  player-badges: false
  assets: false
  gamepasses: false

main-user:
  description: true
  groups: true
  friends: true
  player-badges: false
  assets: false
  gampeasses: false
